version: '3.8'

services:
  grpc:
    build:
      context: .
      dockerfile: Dockerfile
    restart: always 
    ports:
      - "5000:80"
    depends_on:
      - mongo
      - redis
    networks:
      - bamboo
  mongo:
    image: mongo:latest
    restart: unless-stopped
    ports:
      - 27017:27017
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=example
      - MONGO_INITDB_DATABASE=mydatabase
      - MONGO_INITDB_USERNAME=admin
      - MONGO_INITDB_PASSWORD=password
    volumes:
      - ./init-mongo.sh:/docker-entrypoint-initdb.d/init-mongo.sh
    networks:
      - bamboo
  redis:
    image: redis:latest
    restart: always
    ports:
      - 6379:6379
    command: redis-server --save 20 1 --loglevel warning --requirepass redispassword
    networks:
      - bamboo

networks:
  bamboo:
    driver: bridge
